CREATE TABLE IF NOT EXISTS `marriage_certificates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `certificate_no` int(11) NOT NULL,
  `husband_name` varchar(100) NOT NULL,
  `husband_address` text NOT NULL,
  `husband_dob` date NOT NULL,
  `husband_age` int(11) NOT NULL,
  `husband_cast` varchar(50) NOT NULL,
  `husband_photo` varchar(255) NOT NULL,
  `husband_aadhar_no` varchar(12) NOT NULL,
  `husband_aadhar_doc` varchar(255) NOT NULL,
  `wife_name` varchar(100) NOT NULL,
  `wife_address` text NOT NULL,
  `wife_dob` date NOT NULL,
  `wife_age` int(11) NOT NULL,
  `wife_cast` varchar(50) NOT NULL,
  `wife_photo` varchar(255) NOT NULL,
  `wife_aadhar_no` varchar(12) NOT NULL,
  `wife_aadhar_doc` varchar(255) NOT NULL,
  `marriage_date` date NOT NULL,
  `marriage_place` varchar(255) NOT NULL,
  `marriage_card` varchar(255) NOT NULL,
  `witness1_name` varchar(100) NOT NULL,
  `witness1_aadhar_doc` varchar(255) NOT NULL,
  `witness2_name` varchar(100) NOT NULL,
  `witness2_aadhar_doc` varchar(255) NOT NULL,
  `witness3_name` varchar(100) NOT NULL,
  `witness3_aadhar_doc` varchar(255) NOT NULL,
  `registration_date` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `certificate_no` (`certificate_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;